# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name rcpp_hello_world
#' @title Simple cpp code
#' @description Simple cpp code
#' @return a List z
#' @examples
#' \dontrun{
#' rcpp_hello_world()
#' }
#' @export
#' @useDynLib StatComp19086, .registration = TRUE
rcpp_hello_world <- function() {
    .Call(`_StatComp19086_rcpp_hello_world`)
}

#' @name rw_Metropolis
#' @title A Metropolis sampler using Rcpp
#' @description A Metropolis sampler using Rcpp
#' @param N the number of samples
#' @param x0 the number of between-sample random number
#' @param sigma variance
#' @return a List with a random sample of size \code{n} and k
#' @examples
#' \dontrun{
#' sigma <- 2
#' x0 <- 25
#' N <- 2000
#' res <- rw_Metropolis(sigma, x0, N)
#' }
#' @export
#' @useDynLib StatComp19086, .registration = TRUE
rw_Metropolis <- function(sigma, x0, N) {
    .Call(`_StatComp19086_rw_Metropolis`, sigma, x0, N)
}

